name: UI Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run UI Tests
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: Build and test
      run: |
        xcodebuild test -scheme COMP-49X-24-25-PhoneArt-intro-project -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' -testPlan UITests
