name: Intro Project Testing

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Swift
      uses: swift-actions/setup-swift@v1
      
    - name: Get swift version
      run: swift --version
      
    - name: Build
      run: swift build -v
      
    - name: Run tests
      run: swift test -v
